version: '3.4'

services:
  catalogdb:
    image: mongo
    
  basketdb:
    image: redis:alpine
  
  discountdb:
    image: postgres
  
  orderdb:
    image: mcr.microsoft.com/mssql/server:2022-latest
  
  portainer:
    image: portainer/portainer-ce
    
  catalog.api:
    image: ${DOCKER_REGISTERY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile
      
  basket.api:
    image: ${DOCKER_REGISTERY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile
  
  discount.api:
    image: ${DOCKER_REGISTERY-}discountapi
    build:
      context: .
      dockerfile: Services/Discount/Discount.API/Dockerfile

  discount.grpc:
    image: ${DOCKER_REGISTERY-}discountgrpc
    build:
      context: .
      dockerfile: Services/Discount/Discount.Grpc/Dockerfile
      
  ordering.api:
    image: ${DOCKER_REGISTERY-}orderingapi
    build:
      context: .
      dockerfile: Services/Ordering/Ordering.API/Dockerfile

volumes:
  mongo_data:
  portainer_data:
  postgres_data: