version: '3.4'

services:
  catalogdb:
    image: mongo
    
  catalog.api:
    image: ${DOCKER_REGISTERY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile
    
volumes:
  mongo_data:
    